### PR TITLE
chore: [REV-1551] clean up dependencies for Renovate (#510)

### PR DESCRIPTION
**Pull request by BbrSofiane**
* chore: run npm audit fix

* chore: upgrade to @edx/frontend-build@8.1.3 for npm audit

* chore: remove purgecss-webpack-plugin

Required to upgrade @edx/frontend-build.

See https://github.com/edx/frontend-build/releases/tag/v7.0.0

* chore: upgrade to immer@9.0.6 for npm audit

* chore: upgrade to @edx/paragon@16.16.0 for npm audit

* chore: upgrade to mozjpeg@7.1.1 for npm audit

Note: There is a known issue in mozjpeg@7.1.1:

On GitHub, see: imagemin/mozjpeg-bin!67

This may throw errors in the dev build. However, since it is a
devDependency, it should not affect the prod build.

Workarounds:
* Pin mozjpeg@7.1.0 locally.
* `apt-get install nasm` in your frontend-app-payment devstack shell.

Note mozjpeg@7.1.0 contains 1 high vulnerability.

* chore: upgrade to html-webpack-plugin@5.3.2 to fix htmlWebpackPluginAlterChunks error

* chore: upgrade react (&c) for npm audit

* fix: unpin all repos and npm update for renovate prep

* chore: upgrade to audit-ci@5 & husky@7

* chore: upgrade to paragon@16.17

* fix: refresh snapshots after dependency upgrades

* chore: upgrade to form-urlencoded@6.0.5

* chore: upgrade to es-check@6.1.0 for npm audit

* chore: whitelist audit findings after manual review

* fix: sync Makefile precommit with package.json

* fix: add PCI compliance reminders

* chore: update snapshots

* fix: convert react-test-renderer tests to enzyme

Paragon <Input> components employ an accessibility test called
checkHasLabel() that uses forwardRefs.

checkHasLabel() is set to run only in devstack.

react-test-renderer is natively incompatible with forwardRefs:

    https://reactjs.org/docs/test-renderer.html#ideas

Convert react-test-renderer tests to enzyme tests so a jsdom makes
forwardRefs available for the devstack accessibility tests.

* fix: have CI do npm audit last

Audits usually are addressed after all tests have passed.

If audit precede test checks, information about test failure is obscured
by incoming audit findings.

* fix: remove depcheck-id'ed unused dependencies

* fix: upgrade husky

* fix: run npm upgrade & npm dedup

* fix: update owner & reflect removal of Purgecss in README.md

* fix: reword PCI compliance impact check

* chore: npm-force-resolutions to upgrade deps in lockfile

## Checklist
- [ ] Consider PCI compliance impact and whether this PR changes how credit card information is handled.
- [ ] Intend to [release and monitor](https://openedx.atlassian.net/wiki/spaces/RS/pages/1835106870/How+to+contribute+to+our+repositories) this PR promptly after merge.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @BbrSofiane! I've created [OSPR-6281](https://openedx.atlassian.net/browse/OSPR-6281) to keep track of it in JIRA.

As a core committer in this repo, you can merge this once the pull request is approved per the [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.

**Comment by BbrSofiane** [comment]
I've run npm install to fix the CI failure but I keep this pre-commit error:

```
[33mConsider not allowlisting advisories: 1002401, 1002423, 1002465, 1002522, 1002655.[0m
[31mFailed security audit due to high, moderate vulnerabilities.
Vulnerable advisories are: 1004946, 1004967, 1005009, 1005059, 1005174[0m
[31mExiting...[0m
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @edx/frontend-app-payment@0.1.0 audit:whitelisted: `npx audit-ci --config audit-ci.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @edx/frontend-app-payment@0.1.0 audit:whitelisted script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

@davidjoy Can you advice on how to fix this?

cc: @regisb @cmltaWt0

**Comment by natabene** [comment]
@BbrSofiane Thank you for your contribution. Please let me know once this is ready for our review.

**Comment by BbrSofiane** [comment]
Closed in favor of #541

**Comment by edx-webhook** [comment]
@BbrSofiane Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/frontend-app-payment&entry.867055334=https://github.com/edx/frontend-app-payment/pull/538&entry.1484655318=https://github.com/BbrSofiane&entry.752974735=2021-12-15+09:22&entry.1917517419=2021-12-20+16:59&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
